name: Đề xuất
description: Đề xuất tính năng hay nội dung.
title: "[ĐỀ XUẤT]: "
labels: ["đề xuất"]
body:
  - type: markdown
    attributes:
      value: Cảm ơn bạn đã dành thời gian!
  - type: textarea
    id: feature-suggestion
    attributes:
      label: Bạn muốn đề xuất tính tính năng hay nội dung gì?
      placeholder: |
        - Tính năng mới
        - Nội dung mới / Chỉnh sửa nội dung
        - ...
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Lý do bạn đưa ra đề xuất này?
      placeholder: Lý do...
  - type: checkboxes
    id: terms
    attributes:
      label: Hoàn tất đề xuất
      options:
        - label: Tôi đã kiểm tra các đề xuất đã được đăng và đảm bảo rằng đề xuất này chưa tồn tại.
          required: true