name: Câu hỏi
description: Nếu bạn có những thắc mắc cần được trả lời
title: "[HỎI]: "
labels: ["câu hỏi"]
body:
  - type: markdown
    attributes:
      value: Cảm ơn bạn đã dành thời gian!
  - type: textarea
    id: question
    attributes:
      label: Thắc mắc của bạn là gì?
      placeholder: ...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Hoàn tất câu hỏi
      options:
        - label: Tôi đã kiểm tra các câu hỏi đã được đăng và đảm bảo rằng câu hỏi này chưa tồn tại.
          required: true